### ISSUE TITLE
Question on Permissions

### ISSUE THREAD

**Issue by IzzySoft** [robinsrk/flip_2_dnd#1]
Your latest release added a few permissions – and flags, which raise an eyebrow. So I want to kindly ask for clarification:

* what does the app need network permissions for suddenly? I see you've added `INTERNET` and `ACCESS_NETWORK_STATE`
* and especially, what unsecured connections does the app establish? The flag `usesCleartextTraffic` was added.
* in the library section, I see `okhttp` was added, which only makes sense with network connections via HTTP. What for is that needed?

According to the app description, the purpose of the app is to enable/disable DND mode. None of the above should be needed for that. Looking at your changelog, I see for v1.02 (which did ***NOT*** yet have network permissions):

> * GitHub release checking functionality
> * Auto-update notification system

That might violate the inclusion criteria (both, at IzzyOnDroid and at F-Droid) unless it's clearly opt-in and outlines the implications of loading apps directly from there (e.g. bypassing the extra checks performed at each of the mentioned repositories) – I've just checked, the latter is missing, so this **is** a violation. Further, it seems this addition more than tripled the size of your app (from 1.2 MB to now 3.9 MB). Is that really necessary, and worth the size increase? Update checks (and notifications) are performed by the F-Droid clients already, so the app does not need to do that as well.

**Comment by robinsrk** [comment]
> Your latest release added a few permissions – and flags, which raise an eyebrow. So I want to kindly ask for clarification:
> 
> * what does the app need network permissions for suddenly? I see you've added `INTERNET` and `ACCESS_NETWORK_STATE`
> * and especially, what unsecured connections does the app establish? The flag `usesCleartextTraffic` was added.
> * in the library section, I see `okhttp` was added, which only makes sense with network connections via HTTP. What for is that needed?
> 
> According to the app description, the purpose of the app is to enable/disable DND mode. None of the above should be needed for that. Looking at your changelog, I see for v1.02 (which did _**NOT**_ yet have network permissions):
> 
> > * GitHub release checking functionality
> > * Auto-update notification system
> 
> That might violate the inclusion criteria (both, at IzzyOnDroid and at F-Droid) unless it's clearly opt-in and outlines the implications of loading apps directly from there (e.g. bypassing the extra checks performed at each of the mentioned repositories) – I've just checked, the latter is missing, so this **is** a violation. Further, it seems this addition more than tripled the size of your app (from 1.2 MB to now 3.9 MB). Is that really necessary, and worth the size increase? Update checks (and notifications) are performed by the F-Droid clients already, so the app does not need to do that as well.

This is my first app open source app, so maybe i am doing something wrong. In next release i will remove those.

**Comment by IzzySoft** [comment]
Thanks! Whenever in doubt, feel free to ask. Things often aren't simply "black and white", but here I'd say an integrated updater doesn't really fit – especially if the functionality of the app does not require network access, it's better to keep such things out: what isn't there, cannot cause problems :wink:
