### ISSUE TITLE
v1.0.3 No Longer Works on A13 Unihertz Jelly Star

### ISSUE THREAD

**Issue by sanctimoniousape** [robinsrk/flip_2_dnd#2]
As stated in title - v1.0.2 seemed to work well (outside of sound and vibration, but I don't care about that as long as the main function works), but the next release doesn't work at all.

The [Unihertz Jelly Star](https://www.unihertz.com/products/jelly-star?variant=43998790451439) I'm using it on is pretty much a minimally modified Android 13 device (a handful of app management & security apps added), so compatibility hasn't really been an issue outside of apps not designed for its diminutive screen size, which doesn't seem to be a problem here.

**Comment by robinsrk** [comment]
> As stated in title - v1.0.2 seemed to work well (outside of sound and vibration, but I don't care about that as long as the main function works), but the next release doesn't work at all.
> 
> The [Unihertz Jelly Star](https://www.unihertz.com/products/jelly-star?variant=43998790451439) I'm using it on is pretty much a minimally modified Android 13 device (a handful of app management & security apps added), so compatibility hasn't really been an issue outside of apps not designed for its diminutive screen size, which doesn't seem to be a problem here.

Can you be a bit more specific of what things don't work? like the dnd toggling not working? or app crashing or anything?
try toggling the "only when screen off" option in settings and then check if working or not

**Comment by robinsrk** [comment]
> As stated in title - v1.0.2 seemed to work well (outside of sound and vibration, but I don't care about that as long as the main function works), but the next release doesn't work at all.
> 
> The [Unihertz Jelly Star](https://www.unihertz.com/products/jelly-star?variant=43998790451439) I'm using it on is pretty much a minimally modified Android 13 device (a handful of app management & security apps added), so compatibility hasn't really been an issue outside of apps not designed for its diminutive screen size, which doesn't seem to be a problem here.

You can also download the latest release from github releases, v1.0.4, which works perfectly

**Comment by sanctimoniousape** [comment]
> Can you be a bit more specific of what things don't work? like the dnd toggling not working? or app crashing or anything?
> try toggling the "only when screen off" option in settings and then check if working or not

DND didn't work.  Under the previous version, I could show the quick settings panel and watch the DND button activate/deactivate as I moved the phone. No such response under v1.0.3.  Obviously no way to do so with "screen off" option, and outside of calling myself from another phone I couldn't think of another way to test with the screen off.  No crashing, however - so good job there.

>You can also download the latest release from github releases, v1.0.4, which works perfectly

Considering the feedback you received from IzzyOnDroid in the issue reported prior to mine, I prefer to play it safe and wait until they've vetted any future versions.  No offense intended, but I just don't have time for dealing with any potential issues beyond the simple ones. 

Thank you, nonetheless - both for the useful app, as well as the incredibly quick response!

**Comment by robinsrk** [comment]
> > Can you be a bit more specific of what things don't work? like the dnd toggling not working? or app crashing or anything?
> > try toggling the "only when screen off" option in settings and then check if working or not
> 
> DND didn't work. Under the previous version, I could show the quick settings panel and watch the DND button activate/deactivate as I moved the phone. No such response under v1.0.3. Obviously no way to do so with "screen off" option, and outside of calling myself from another phone I couldn't think of another way to test with the screen off. No crashing, however - so good job there.
> 
> > You can also download the latest release from github releases, v1.0.4, which works perfectly
> 
> Considering the feedback you received from IzzyOnDroid in the issue reported prior to mine, I prefer to play it safe and wait until they've vetted any future versions. No offense intended, but I just don't have time for dealing with any potential issues beyond the simple ones.
> 
> Thank you, nonetheless - both for the useful app, as well as the incredibly quick response!

Yeah updated another version, waiting for it to get live on izzyondroid.
