### ISSUE TITLE
[FR] User-enabled DND

### ISSUE THREAD

**Issue by teemue** [robinsrk/flip_2_dnd#3]
thanks for the app!

I often have DND mode on while using phone. When using the app,, DND mode gets disabled. Is it possible to add an option to let DND mode be enabled, if the user has enabled it?

**Comment by robinsrk** [comment]
> thanks for the app!
> 
> I often have DND mode on while using phone. When using the app,, DND mode gets disabled. Is it possible to add an option to let DND mode be enabled, if the user has enabled it?

That's really nice idea. I would try to implement this in future update
