### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by BabyOilJohnson** [robinsrk/flip_2_dnd#5]
There's a slight misalignment between the text and the toggle.
<details><summary>Screenshot</summary>
<p>

![Screenshot_20241208-230605_Flip 2 DND](https://github.com/user-attachments/assets/077bfc18-cf97-4342-9b88-1c57605c8215)

</p>
</details>

**Comment by robinsrk** [comment]
Hope it fixed, check the newest version from github, or wait till it is upstreamed in izzyondroid repo.
